import { Router } from 'express';

const holidays = [
    { id: 'PKG001', name: 'Golden Rajasthan Odyssey', destination: 'Rajasthan', image: 'https://s7ap1.scene7.com/is/image/incredibleindia/2-mehrangarh-fort-jodhpur-rajasthan-city-hero?qlt=82&ts=1726660925514', duration: '7 Days / 6 Nights', cities: ['Jaipur', 'Jodhpur', 'Udaipur', 'Jaisalmer'], price: 28999, originalPrice: 38000, rating: 4.7, reviews: 1243, category: 'Heritage', groupSize: '2-12', inclusions: ['Hotels', 'Breakfast', 'Dinner', 'All Transfers', 'Guide', 'Entry Tickets'], exclusions: ['Flights', 'Lunch', 'Personal Expenses', 'Insurance'], highlights: ['Amber Fort', 'Mehrangarh Fort', 'Lake Pichola Sunset', 'Sam Sand Dunes Camel Ride', 'City Palace'], itinerary: [{ day: 1, title: 'Arrival in Jaipur', description: 'Welcome to the Pink City! Check-in and evening at leisure. Welcome dinner at heritage restaurant.' }, { day: 2, title: 'Jaipur Sightseeing', description: 'Explore Amber Fort, Hawa Mahal, Jantar Mantar. Camel ride at sunset.' }, { day: 3, title: 'Jaipur to Jodhpur', description: 'Drive to the Blue City. Visit Mehrangarh Fort and Jaswant Thada.' }, { day: 4, title: 'Jodhpur to Udaipur', description: 'Scenic drive through Rajasthan. Evening boat ride on Lake Pichola.' }, { day: 5, title: 'Udaipur Sightseeing', description: 'Visit City Palace, Saheliyon-ki-Bari, and Bagore-ki-Haveli.' }, { day: 6, title: 'Udaipur to Jaisalmer', description: 'Drive to the Golden City. Camel safari at Sam Sand Dunes. Desert night under stars.' }, { day: 7, title: 'Departure', description: 'Explore Jaisalmer Fort. Transfer to Jaisalmer station/airport.' }] },
    { id: 'PKG002', name: 'Kerala Backwaters Bliss', destination: 'Kerala', image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&h=500&fit=crop', duration: '5 Days / 4 Nights', cities: ['Kochi', 'Munnar', 'Alleppey'], price: 19999, originalPrice: 26000, rating: 4.8, reviews: 987, category: 'Nature', groupSize: '2-8', inclusions: ['Hotels', 'Houseboat', 'All Meals on Houseboat', 'Transfers', 'Sightseeing'], exclusions: ['Flights', 'Meals at Hotels', 'Personal Expenses'], highlights: ['Houseboat Cruise', 'Tea Gardens', 'Athirappilly Falls', 'Mattancherry Palace', 'Elephant Encounter'], itinerary: [{ day: 1, title: 'Arrive Kochi', description: 'Explore Fort Kochi, Chinese Fishing Nets, and Mattancherry.' }, { day: 2, title: 'Kochi to Munnar', description: 'Drive through scenic ghats. Visit Eravikulam National Park and tea gardens.' }, { day: 3, title: 'Munnar to Alleppey', description: 'Board your luxury houseboat on the backwaters.' }, { day: 4, title: 'Backwater Cruise', description: "Full day cruising through Kerala's enchanting backwater channels." }, { day: 5, title: 'Departure', description: 'Morning yoga and breakfast on houseboat. Transfer to Kochi.' }] },
    { id: 'PKG003', name: 'Himalayan Splendour', destination: 'Himachal Pradesh', image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&h=500&fit=crop', duration: '6 Days / 5 Nights', cities: ['Shimla', 'Manali', 'Rohtang Pass'], price: 24999, originalPrice: 32000, rating: 4.6, reviews: 2104, category: 'Adventure', groupSize: '2-15', inclusions: ['Hotels', 'Breakfast', 'Dinner', 'All Transfers', 'Adventure Activities'], exclusions: ['Flights', 'Lunch', 'Snow Activities Equipment'], highlights: ['Rohtang Pass Snow', 'Solang Valley Adventure', 'Ridge Shimla', 'Hadimba Temple', 'Paragliding'], itinerary: [{ day: 1, title: 'Arrive Shimla', description: 'Explore The Ridge and Mall Road.' }, { day: 2, title: 'Shimla Local + Kufri', description: 'Day trip to Kufri for snow activities.' }, { day: 3, title: 'Shimla to Manali', description: 'Scenic drive through Kullu Valley.' }, { day: 4, title: 'Manali Sightseeing', description: 'Visit Hadimba Devi Temple, Old Manali.' }, { day: 5, title: 'Rohtang Pass / Solang Valley', description: 'Snow activities, skiing, paragliding at Solang Valley.' }, { day: 6, title: 'Departure', description: 'Leisure morning. Transfer to Bhuntar Airport.' }] },
    { id: 'PKG004', name: 'Goa Beach Fiesta', destination: 'Goa', image: 'https://images.unsplash.com/photo-1587922546307-776227941871?w=800&h=500&fit=crop', duration: '4 Days / 3 Nights', cities: ['North Goa', 'South Goa'], price: 14999, originalPrice: 19000, rating: 4.4, reviews: 3210, category: 'Beach', groupSize: '2-10', inclusions: ['Resort Stay', 'Breakfast', 'Airport Transfers', 'North & South Goa Tour'], exclusions: ['Flights', 'Lunches & Dinners', 'Water Sports', 'Personal Expenses'], highlights: ['Calangute Beach', 'Baga Nightlife', 'Dudhsagar Falls', 'Old Goa Churches', 'Cruise'], itinerary: [{ day: 1, title: 'Arrive Goa', description: 'Airport pickup. Relax at Calangute Beach. Sunset cruise.' }, { day: 2, title: 'North Goa Sightseeing', description: 'Fort Aguada, Chapora Fort, Anjuna Flea Market.' }, { day: 3, title: 'South Goa & Dudhsagar', description: 'Visit Dudhsagar Falls, Spice Plantation, Old Goa churches.' }, { day: 4, title: 'Departure', description: 'Morning beach walk. Airport/station transfer.' }] },
    { id: 'PKG005', name: 'Andaman Island Paradise', destination: 'Andaman & Nicobar', image: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&h=500&fit=crop', duration: '6 Days / 5 Nights', cities: ['Port Blair', 'Havelock Island', 'Neil Island'], price: 32999, originalPrice: 44000, rating: 4.9, reviews: 876, category: 'Beach', groupSize: '2-8', inclusions: ['Hotels', 'All Meals', 'Ferries', 'Scuba Diving', 'Sightseeing'], exclusions: ['Flights to Port Blair', 'Personal Expenses'], highlights: ['Radhanagar Beach', 'Scuba Diving', 'Glass-bottom Boat', 'Cellular Jail', 'Snorkeling'], itinerary: [{ day: 1, title: 'Port Blair Arrival', description: 'Visit Cellular Jail. Evening Sound & Light Show.' }, { day: 2, title: 'Port Blair to Havelock', description: 'Ferry to Havelock. Visit Radhanagar Beach.' }, { day: 3, title: 'Havelock Adventures', description: 'Scuba diving at Elephant Beach. Glass-bottom boat ride.' }, { day: 4, title: 'Havelock to Neil Island', description: 'Ferry to Neil Island. Natural Bridge, Bharatpur Beach.' }, { day: 5, title: 'Neil to Port Blair', description: 'Return to Port Blair. Shopping at Aberdeen Bazaar.' }, { day: 6, title: 'Departure', description: 'Airport transfer from Port Blair.' }] },
];

const router = Router();

// GET /api/holidays  — query: destination, category, minPrice, maxPrice
router.get('/', (req, res) => {
    let results = [...holidays];
    const { destination, category, minPrice, maxPrice } = req.query;
    if (destination) results = results.filter(p => p.destination.toLowerCase().includes(destination.toLowerCase()));
    if (category) results = results.filter(p => p.category.toLowerCase() === category.toLowerCase());
    if (minPrice) results = results.filter(p => p.price >= Number(minPrice));
    if (maxPrice) results = results.filter(p => p.price <= Number(maxPrice));
    res.json({ success: true, count: results.length, data: results });
});

// GET /api/holidays/:id
router.get('/:id', (req, res) => {
    const pkg = holidays.find(p => p.id === req.params.id);
    if (!pkg) return res.status(404).json({ success: false, message: 'Package not found' });
    res.json({ success: true, data: pkg });
});

export default router;
